steps:
  # Build the Go server
  - name: 'golang:1.25'
    entrypoint: 'go'
    args: ['build', '-o', 'resume-server', 'server/main.go']
    dir: '.'

  # Build the React client
  - name: 'node:24'
    entrypoint: 'npm'
    args: ['install']
    dir: 'resume-client'
  - name: 'node:24'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'resume-client'

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/resume/resume-oner:$SHORT_SHA'
      - '.'
    dir: '.'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-east1-docker.pkg.dev/$PROJECT_ID/resume/resume-oner:$SHORT_SHA',
      ]

  # Deploy the container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'resume-oner'
      - '--image'
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/resume/resume-oner:$SHORT_SHA'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
images:
  - 'us-east1-docker.pkg.dev/$PROJECT_ID/resume/resume-oner:$SHORT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
